# Generated by Django 5.1.2 on 2024-10-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourfeedback',
            name='destination_rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tourfeedback',
            name='driver_support',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tourfeedback',
            name='ground_support_team',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tourfeedback',
            name='guide_support',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tourfeedback',
            name='hotels_chosen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tourfeedback',
            name='tour_services_rating',
            field=models.FloatField(),
        ),
    ]
